// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJdCb2rGFB4ikJ3AsfhiLYeFrufYaYbA',
    appId: '1:693454267557:web:680aebf32c87e8be29994c',
    messagingSenderId: '693454267557',
    projectId: 'evenly1-a97ba',
    authDomain: 'evenly1-a97ba.firebaseapp.com',
    storageBucket: 'evenly1-a97ba.firebasestorage.app',
    measurementId: 'G-36S2BSXWSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnxbPi6VlpWTvtWxi4tCNqi2nE1lSE4Z8',
    appId: '1:693454267557:android:8a39e1a6f2b14acf29994c',
    messagingSenderId: '693454267557',
    projectId: 'evenly1-a97ba',
    storageBucket: 'evenly1-a97ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrZELQlyVfWkFt-hbLWc0q9c5f84LHeQ',
    appId: '1:693454267557:ios:c7be876c6122ae2529994c',
    messagingSenderId: '693454267557',
    projectId: 'evenly1-a97ba',
    storageBucket: 'evenly1-a97ba.firebasestorage.app',
    iosBundleId: 'com.example.evenly1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOrZELQlyVfWkFt-hbLWc0q9c5f84LHeQ',
    appId: '1:693454267557:ios:c7be876c6122ae2529994c',
    messagingSenderId: '693454267557',
    projectId: 'evenly1-a97ba',
    storageBucket: 'evenly1-a97ba.firebasestorage.app',
    iosBundleId: 'com.example.evenly1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJdCb2rGFB4ikJ3AsfhiLYeFrufYaYbA',
    appId: '1:693454267557:web:730d82405b8cb08f29994c',
    messagingSenderId: '693454267557',
    projectId: 'evenly1-a97ba',
    authDomain: 'evenly1-a97ba.firebaseapp.com',
    storageBucket: 'evenly1-a97ba.firebasestorage.app',
    measurementId: 'G-QK9D302FNM',
  );
}
